### ISSUE TITLE
Add signing API

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#205]
- [x] #206: Add Ed25519 signing (done by @djc).
- [x] #207 Add ECDSA P-256 signing.
- [x] #208 Add RSA PKCS#1 1.5 signing (done by @djc).
- [x] #213 Add RSA PSS signing.
- [x] #209 Add ECDSA P-384 signing.

**Comment by briansmith** [comment]
The signing function should be something like:

```
ring::signature::sign(key: &ring::signature::SigningKey, msg: ring::input::Input) -> ring::signature::Signature { }
```

`ring::signature::Signature` should probably be a lot like `ring::digest::Digest`, a fixed-sized buffer convertible to a slice.

`SigningKey` should look a lot like `ring::hmac::SigningKey`. Note in particular that it needs to store the private key (for ECC, things, just use `ring::ec::PrivateKey`) *and* it needs to cache the computed public key, so it doesn't need to be recomputed over and over.

The main issue is that RSA signatures are large (256 bytes vs 32/48 bytes for ECC signatures), RSA public keys are huge (2048-8192 bits, plus change), and RSA private keys are *giant*. So, for RSA, we probably want to have `reference to a heap-allocated things, instead of expanding the inline fixed-sized buffers to accommodate things.

See the issues linked above for algorithm-/curve- specific concerns.

**Comment by briansmith** [comment]
We should almost definitely do these in the order presented above. At the very least, we should do Ed25519 first because it is by far the simplest to implement.

**Comment by briansmith** [comment]
Creating a good generic signing API is difficult because:

1. ECDSA and RSA require a `SecureRandom` to generates nonces/blndings, but Ed25519 doesn't, 
2. ECDSA and RSA are parameterized by digest algorithm, and one might use the same private key with multiple digest algorithms in practice. However, Ed25519 only works with SHA-512.
3. ECDSA and RSA need their `sign` functions to return `Result<Signature, ()>` because they can fail, but Ed25519 cannot fail (IIRC) so it should just return `Signature`.

So, I suggest that we punt on the generic API for now. Instead, users that need to support mutliple key types can define their own wrappers around whatever algorithm-specific APIs we create. Then, later, we can learn from what people are doing and create a usable general interface, maybe.

**Comment by briansmith** [comment]
All the issues tracked in the summary have been closed as all of Ed25519/P-256/P-384/RSA-PKCS#1/RSA-PSS signing have been implemented, so I'm closing this.

The signing API needs to be improved and made more generic, but we should do those improvements in other issues/PRs.
