### ISSUE TITLE
Improve RSA signing

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#225]
Roughly in order of priority:
- [ ] Get rid of the undefined behavior in `BN_mod_exp_consttime`, caused by strict aliasing violations.
- [x] Get rid of the unnecessary reductions at the start (and end?) of `BN_mod_exp_consttime`. Done in 52879da80d16397f5dd78f620b53c0227e8cae94.
- [ ] `BN_reduce_montgomery` should be reviewed and tested. I believe it can be simplified to a single multiplication.
- [ ] We should run BoringSSL's fuzz tests against the private key parser.
- [x] `GFp_rsa_private_transform` should be redone in Rust: #365.
- [x] The blinding logic should get redone in Rust, replacing blinding.c completely: #364, #372.
- [ ] Add tests for keys that aren't multiples of 1024 bits.
- [ ] Add support (and tests) for keys larger than 4096 bits.
- [x] At least for PSS, and maybe PKCS#1 1.5, it seems we can reduce allocations in the application of the padding; we should do that. Here's the key point from #262: "Instead of setting out to "PS || 0x01 || salt" and then masking it with db_mask, why not fill out with the MGF1 output and then mask "PS || 0x01 || salt" onto it? Wouldn't this avoid the need for the extra buffer?": [Done](https://github.com/briansmith/ring/blame/master/src/rsa/padding.rs#L228-L250).

**Comment by briansmith** [comment]
I factored out some of the bullet points in the initial comment into their own issues. Besides the things noted above, there are many [issues tagged "rsa"](https://github.com/briansmith/ring/issues?q=is%3Aissue%20is%3Aopen%20label%3Arsa), most of which are about RSA signing.

**Comment by briansmith** [comment]
Closing this since the remaining issues are each tracked separately.
