### ISSUE TITLE
Simplify RSA signing code

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#99]
Note that some of these refactorings are only valid because *ring* doesn't use the `RSA` struct for verifying signatures, only for signing and decryption.

* [x] Drop support for signing or decrypting with a key that only has `n` and `d` or only `n`, `d`, and `e`. Instead, we'll require that any such keys be converted to the full PKCS#8 form before they can be used in *ring*.
* [x] Remove `rsa_get_public_exp` in blinding.c. Instead, just fail if `rsa->e` is `NULL`.
* [x] Remove all uses of `BN_with_flags(..., BN_FLG_CONSTTIME)` in the RSA code. Instead, set the `BN_FLG_CONSTTIME` flag on `rsa->n` and other members as required, at the time they are assigned.
* [x] At the time an `RSA` is constructed (using `RSA_generate` or reading in a PKCS#8 file), compute `rsa->mont_n`. Then, remove the lazy initialization of that member. In particular, do this without regard to the `RSA_FLAG_CACHE_PUBLIC` flag, which should be removed. Note that at these times of construction, there is no need for locking, so there's no need to use `BN_MONT_CTX_set_locked`; `BN_MONT_CTX_set` can be used instead. Hopefully this will allow us to remove `BN_MONT_CTX_set_locked` completely.
* [x] Replace `BN_mod`/`BN_div` operations with Montgomery reductions. (in progress by @briansmith)
* [x] Drop the attempt to recover from CRT faults when verifying the just-signed value (pending BoringSSL review).
* [ ] Improve/simplify the RSA blinding code: #144 
* [x] Require p > q and simplify the code accordingly. See https://crypto.stackexchange.com/a/22661. (In progress by @briansmith)
* [ ] Add tests for the corner cases mentioned in https://crypto.stackexchange.com/a/22661.

All of these should be done in separate commits.

**Comment by frewsxcv** [comment]
>  Remove all uses of BN_with_flags(..., BN_FLG_CONSTTIME) in the RSA code. Instead, set the BN_FLG_CONSTTIME flag on rsa->n and other members as required, at the time they are assigned.

For reference:

```c
void BN_with_flags(BIGNUM *out, const BIGNUM *in, int flags) {
  memcpy(out, in, sizeof(BIGNUM));
  out->flags &= ~BN_FLG_MALLOCED;
  out->flags |= BN_FLG_STATIC_DATA | flags;
}
```

Correct me if I'm wrong, but this function:

* Clones the `in` `BIGNUM` into `out`
* Unsets the `BN_FLG_MALLOCED` flag in `out`
* Sets the `BN_FLG_STATIC_DATA` and `flags` flags in `out`

Considering that, it seems like if we replaced these steps with just "set BN_FLG_CONSTTIME flag on rsa->n", that it would result in a different net set of operations being performed on `out`. Am I misunderstanding something?

**Comment by briansmith** [comment]
`RSA_parse_private_key` and calls `parse_integer` to initialize `n` and `e` and other values. That `parse_integer` function should be changed to set the `BN_FLG_CONSTTIME` flag. Similarly, `RSA_generate` initializes all those values with randomly-generated values; `RSA_generate` should set the `BN_FLG_CONSTTIME` flag on all of them.

Then those `BN_with_flags` calls would be redundant, since the source `BIGNUM` would already have those flags set.

**Comment by frewsxcv** [comment]
Given [this test case](https://github.com/frewsxcv/ring/blob/7605b2f6daabc59068cabc8e085e888b5a7ea5ff/crypto/rsa/rsa_test.cc#L345-L393), on [this line](https://github.com/frewsxcv/ring/blob/7605b2f6daabc59068cabc8e085e888b5a7ea5ff/crypto/rsa/rsa_test.cc#L355-L358), `rsa->d` gets initialized via a hex value. Then, the following functions get executed:

1. [`RSA_sign`](https://github.com/briansmith/ring/blob/6cc1d688381b476c108bf4cdd38575c9e4d65045/crypto/rsa/rsa_test.cc#L367-L368)
1. [`RSA_sign_raw`](https://github.com/briansmith/ring/blob/6cc1d688381b476c108bf4cdd38575c9e4d65045/crypto/rsa/rsa.c#L291-L292)
1. [`rsa_private_transform`](https://github.com/briansmith/ring/blob/6cc1d688381b476c108bf4cdd38575c9e4d65045/crypto/rsa/rsa_impl.c#L337)

The last function results in [this assertion failing](https://github.com/briansmith/ring/commit/7605b2f6daabc59068cabc8e085e888b5a7ea5ff#diff-79612b67fb199ee044640db007fbadb0R600) since (presumably) the `rsa->d` value has not been touched since originally being set. At what point in this should the `BN_FLG_CONSTTIME` flag get set?

**Comment by briansmith** [comment]
The first item in this issue is "Drop support for signing or decrypting with a key that only has n and d or only n, d, and e. Instead, we'll require that any such keys be converted to the full PKCS#8 form before they can be used in ring." That test is testing the case where a key "only has n and d" given. So, that particular test can just be removed when the support for signing with only n and d given is removed.

The BN_FLG_CONSTTIME flag on rsa->n and other members should be set at the time they are initialized. In the case of the tests in that file, it is probably a good idea to create a wrapper around `BN_hex2bn` that takes the hex string and the expected flags, and returns a BIGNUM with the given value and the given flags. Then, use it pervasively in the tests, everywhere except where a public key for RSA signature *verification* is being constructed.

**Comment by frewsxcv** [comment]
https://github.com/briansmith/ring/compare/master...frewsxcv:bn-with-flags

@briansmith When you have a moment, can you hastily look over this and make sure I'm going down the right path here?

**Comment by briansmith** [comment]
I removed this item:
> [ ] Remove RSA->lock. (Hopefully all of the above changes will remove all uses of it.)

Because `RSA::lock` is used by the blinding code.

I did change the code to eagerly initialize `mont_n`, `mont_p`, and `mont_q`, removing the use of the lock from them, in order to make progress on some other non-RSA-specific work. In order to do that, I changed the way `RSA`s are constructed so that they can only be constructed (from external code) using `RSA_generate` or by reading in a private key file. However, I didn't make the RSA structure opaque yet.

@frewsxcv I think that the `rsa_new_end` function I added is a good place to set the `BN_FLG_CONSTTIME` on all the RSA members. Sorry about the merge conflict this will generate; I hope it simplifies your work though.

**Comment by briansmith** [comment]
I removed the good-first-bug tag on this. There are several changes to this code pending in the BoringSSL queue, and so (hopefully) the BoringSSL merge will result in tons of churn. We should re-evaluate this once the BoringSSL changes merge.

**Comment by briansmith** [comment]
>  Improve/simplify the RSA blinding code: #144

All the old RSA blinding code was removed. A minimal implementation was added and there are other issues to track improving that minimal implementation.

> Add tests for the corner cases mentioned in https://crypto.stackexchange.com/a/22661.

I moved this to #220.

And, otherwise, it was all done!
